"""empty message

Revision ID: 15d2a2358740
Revises: 5342041b3f2c
Create Date: 2025-09-05 09:43:33.651427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d2a2358740'
down_revision = '5342041b3f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('google_refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('google_access_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_access_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('google_refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('google_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
