"""empty message

Revision ID: 760012976638
Revises: e513b1778caa
Create Date: 2025-09-15 09:23:49.394034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760012976638'
down_revision = 'e513b1778caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_task_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_task_group_id_fkey', 'task_group', ['task_group_id'], ['id'])

    # ### end Alembic commands ###
