"""empty message

Revision ID: 81803c1bfd52
Revises: 9187491e1250
Create Date: 2025-09-03 09:28:50.902945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81803c1bfd52'
down_revision = '9187491e1250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrencia', sa.Integer(), nullable=False))
        batch_op.drop_column('recurencia')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurencia', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('recurrencia')

    op.drop_table('group')
    # ### end Alembic commands ###
