"""empty message

Revision ID: 8e132acd9506
Revises: 81803c1bfd52
Create Date: 2025-09-03 09:36:32.867225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e132acd9506'
down_revision = '81803c1bfd52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('group_event_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('group_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('group_task_id_fkey', 'task', ['task_id'], ['id'])
        batch_op.create_foreign_key('group_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
