"""empty message

Revision ID: 9187491e1250
Revises: 0763d677d453
Create Date: 2025-08-30 15:48:05.842669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9187491e1250'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('recurencia', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displayName', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('signup_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('rol', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_session', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('google_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('google_refresh_token', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('google_access_token', sa.String(length=255), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('google_access_token')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_id')
        batch_op.drop_column('status')
        batch_op.drop_column('last_session')
        batch_op.drop_column('rol')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('signup_date')
        batch_op.drop_column('name')
        batch_op.drop_column('displayName')

    op.drop_table('task')
    op.drop_table('event')
    # ### end Alembic commands ###
