"""empty message

Revision ID: c9f9a13ed10b
Revises: 8e374c911066
Create Date: 2025-09-21 22:54:28.160877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f9a13ed10b'
down_revision = '8e374c911066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_day', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('event_calendar_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'calendar', ['calendar_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_calendar_id_fkey', 'calendar', ['calendar_id'], ['id'])
        batch_op.drop_column('all_day')

    # ### end Alembic commands ###
