"""empty message

Revision ID: e02e902d84aa
Revises: 737f6f6762dc
Create Date: 2025-09-16 16:46:51.248225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02e902d84aa'
down_revision = '737f6f6762dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('task_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('task_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
