"""empty message

Revision ID: e513b1778caa
Revises: ec50ea43f72b
Create Date: 2025-09-15 09:13:39.989865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e513b1778caa'
down_revision = 'ec50ea43f72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'task_group', ['task_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('task_group_id')

    # ### end Alembic commands ###
