"""empty message

Revision ID: ec50ea43f72b
Revises: f9afe306ae62
Create Date: 2025-09-15 09:09:54.272058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec50ea43f72b'
down_revision = 'f9afe306ae62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('event_task_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('event_task_group_id_fkey', 'task_group', ['task_group_id'], ['id'])

    # ### end Alembic commands ###
