"""empty message

Revision ID: f25f4988093e
Revises: 760012976638
Create Date: 2025-09-15 09:34:41.278318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25f4988093e'
down_revision = '760012976638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_calendar_id_fkey', type_='foreignkey')
        batch_op.drop_column('calendar_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('task_calendar_id_fkey', 'calendar', ['calendar_id'], ['id'])

    # ### end Alembic commands ###
